### ISSUE TITLE
Not able to save snippet with dollar $ sign

### ISSUE THREAD

**Issue by Terrorboy** [Afzal7/syncrow#1]
```
SublimeLinter: WARNING: phpcs cannot locate 'phpcs'
2018-04-19 09:38:54,995 - WARNING - phpcs cannot locate 'phpcs'
```

AutoComplete does not work.
The letters disappear.

---

Can I make it work regardless of document properties?
I would also like to be able to enter comments.

**Comment by Afzal7** [comment]
Hi @Terrorboy ,

Can you share the code that you tried adding to syncrow.


> Can I make it work regardless of document properties?
> I would also like to be able to enter comments.

Can you elaborate this a bit it sounds interesting.

Thanks.

**Comment by Terrorboy** [comment]
add => (https://github.com/Afzal7/syncrow) Usage same
![set_snippet](https://user-images.githubusercontent.com/5427199/39040216-d9bf7038-44c1-11e8-859b-7258ee838fa8.gif)

**Template name: ajax
(Do not specify extension)**

result
![1](https://user-images.githubusercontent.com/5427199/39040321-051d6c4e-44c2-11e8-9a50-d63cee1648f3.png)

**Comment by Afzal7** [comment]
Hi @Terrorboy ,

**I have fixed the issue**. You can update your package or it will updated automatically in some time.

**Create a new snippet with a different name, the old one still wont work**. Let me know if everything is cool.

The issue is not related to what is printed in your console, **its actually because of the dollar sign** which is used for string interpolation by sublime.

I am changing the name of the issue.

Thanks.

**Comment by Terrorboy** [comment]
Thank you.
